### ISSUE TITLE
Not able to access robots.txt from student machine.

### ISSUE THREAD

**Issue by urakesh661** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#1]
Hi,

I am facing an issue due to which i am only able to access the landing page of the website installed on azure platform and not the http://azure-vm-ip/robots.txt from the students machine 
Able to access robots.txt file from the azure machine itself.

Also ,i am able to view the below image:

http://azure-vm-ip/img/testimonials-3.jpg from student machine

Can someone please suggest.

Thanks,

Rakesh Kirola

**Comment by riyazwalikar** [comment]
Hi,

This is very likely due to the app not being visible to the student machine.

In the `/documentation/bapazure/cloud-compute/setting-up-azure-target.md` chapter, under `Setting up the Web server and the App`, step 9 instructs you to open port 80 to the attacker machine. You can then access the application using Firefox > SOCKS Proxy to Attacker Machine > Azure IP.

You can use the following to verify your access:
1. Verify if the app is setup properly on the Azure VM by using a browser on the Azure VM (via RDP) and browsing to `http://127.0.0.1/sysadmin/`. If you see a login page, the app is setup properly and the fix is on the Firewall side or your local student machine. Read further.
2. Verify if the Azure VM Port 80 is visible to the Attacker machine (using Azure Networking as described)
3. Verify if you have connected to the Attacker machine using SSH port forwarding from the student machine
4. Verify if Firefox on your student machine is configured to connect to SOCKS proxy under Preferences/Settings
5. If you are using Burp, verify if Burp is connected to SOCKS proxy 127.0.0.1 9090 (or the port used in -D option in SSH) under `User Options` tab of Burp

I have updated the documentation to make the usage of placeholders a little more clearer.

Let us know if the above verification steps don't work.

**Comment by urakesh661** [comment]
Hi,

Opening port 80 on azure machine for student ip resolved the issue.

Thanks!
