### ISSUE TITLE
{"Code":"InternalServerError","Message":"An internal server error occurred."} 

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#17]
Hi appsecco,

Thank you for your help with previous queries. I faced another one during the testing of Lambda.

I've successfully deployed lambda using:
**deploy-awslambda**
When i try to query it i get following:
{"Code":"InternalServerError","Message":"An internal server error occurred."} 

My query:
curl "https://something-api.us-east-1.amazonaws.com/api/string"

**Comment by riyazwalikar** [comment]
I'm assuming you are using the URL "https://something-api.us-east-1.amazonaws.com/api/string" because you do not want to reveal the Lambda endpoint here on Github.

However, if the query that you have posted is the exact query that you are making, then replace the URL with the URL of the lambda endpoint which will be printed after you run the `deploy-awslambda` command. Then follow the documentation at https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/blob/master/documentation/cloud-compute/attacking-serverless-lambda-endpoints.md to perform command injection etc.

**Comment by testacc0808** [comment]
yes, i do not want to reveal. i replaced only word "something"

**Comment by riyazwalikar** [comment]
Login to the AWS console and go to Services > Lambda.

For the lambda that is created, change the environment to Python 2.7 in the web interface.

This has been filed as an issue before. Recommend going through past issues to see if anyone else has faced this and if a resolution was reached :)

Similar issue - https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/issues/3

**Comment by testacc0808** [comment]
now, i have another question because i can't find web interface from my console :)

![image](https://user-images.githubusercontent.com/64963907/83896286-7a727880-a786-11ea-98aa-b60e15585c1a.png)

This is the script after executing "deploy-awslambda"

**Comment by riyazwalikar** [comment]
You are in the wrong region here. You need to switch to US-East-1 region. Refer to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions

Click on the Lambda function once it is visible in the console and change the environment to Python 2.7.

**Comment by testacc0808** [comment]
Thank you for your help @riyazwalikar 
That was an issue. Resolved ;)
