### ISSUE TITLE
url typos in documentation/cloud-compute/application-misconfigurations.md

### ISSUE THREAD

**Issue by kbb29** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#5]
documentation/cloud-compute/application-misconfigurations.md lines 46 and 50

"public-site-" should be "publicsite-"

**Comment by kbb29** [comment]
are issues or PRs better for reporting this sort of typo?

**Comment by D33van** [comment]
ubuntu @ adorable-street :$ deploy-cloudhacker 

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "aws": failed to create plugin dir .terraform/plugins/linux_amd64: mkdir .terraform: permission denied.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.aws: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

**Comment by D33van** [comment]
how to fix this issues

**Comment by riyazwalikar** [comment]
> are issues or PRs better for reporting this sort of typo?

Fixed. Either would be okay, as long as the content improves :)

**Comment by riyazwalikar** [comment]
> ubuntu @ adorable-street :$ deploy-cloudhacker
> 
> Initializing provider plugins...
> 
> * Checking for available provider plugins on https://releases.hashicorp.com...
> 
> Error installing provider "aws": failed to create plugin dir .terraform/plugins/linux_amd64: mkdir .terraform: permission denied.
> 
> Terraform analyses the configuration and state and automatically downloads
> plugins for the providers used. However, when attempting to download this
> plugin an unexpected error occured.
> 
> This may be caused if for some reason Terraform is unable to reach the
> plugin repository. The repository may be unreachable if access is blocked
> by a firewall.
> 
> If automatic installation is not possible or desirable in your environment,
> you may alternatively manually install plugins by downloading a suitable
> distribution package and placing the plugin's executable file in the
> following directory:
> terraform.d/plugins/linux_amd64
> 
> Plugin reinitialization required. Please run "terraform init".
> Reason: Could not satisfy plugin requirements.
> 
> Plugins are external binaries that Terraform uses to access and manipulate
> resources. The configuration provided requires plugins which can't be located,
> don't satisfy the version constraints, or are otherwise incompatible.
> 
> 1 error(s) occurred:
> 
> * provider.aws: no suitable version installed
>   version requirements: "(any version)"
>   versions installed: none

Have created a new issue for this - https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/issues/6. Please track this there.
