### ISSUE TITLE
deploy-cloudhacker

### ISSUE THREAD

**Issue by esrkrishna** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#9]
Hi,

I am also getting below error when trying to run command "deploy-cloudhacker". Could you please help me. 
![cloud error](https://user-images.githubusercontent.com/37097377/80172874-051a6200-85a3-11ea-8ceb-bd4b41319136.PNG)

**Comment by 0xbharath** [comment]
The error seems to happen because the AWS credentials you're using within Terraform are missing some form of IAM permissions. You need an IAM User with Administrator access to run these deploy scripts.

Can you verify if you created an IAM Admin user and created a named profile using AWS CLI in the student VM correctly? Following are the sections that cover it - 

1. "Setting Up" > "Creating an IAM admin user"
2. "Setting up" > "Access to AWS CLI"

**Comment by 0xbharath** [comment]
I'm closing this issue for now. Please feel free to continue the discussion if this issue is not resolved.

**Comment by 0xbharath** [comment]
Can we close this issue? In case it isn't resolved then we can reopen it.

**Comment by riyazwalikar** [comment]
Closing this after 10 days since last activity. @esrkrishna please reopen if issue not resolved.
